### ISSUE TITLE
Random question marks in Omega's opening message

### ISSUE THREAD

**Issue by Kadaeux** [Beyond-the-Relays/beyond_the_relays#3]
![image](https://user-images.githubusercontent.com/9507684/142010626-9d1d9cce-8303-47a0-96f9-c8534891b324.png)
![image](https://user-images.githubusercontent.com/9507684/142010648-b5219571-dc7a-4c86-8fbb-e449b9fc33f2.png)

**Comment by Revan67** [comment]
Confirmed issue. Foreign characters are present in the localization files. 

` trait_pc_dextro_continental_preference_desc:0 "§LClimate preference is determined by eons of evolution, design, or skillful genetic manipulation.§!"`

**Comment by Revan67** [comment]
This has been fixed in the code, will be available in the next beta build.
