### ISSUE TITLE
Anadius

### ISSUE THREAD

**Issue by mstonefield** [Beyond-the-Relays/beyond_the_relays#37]
Star is of wrong class. Shows as Class M Red Giant. Should be Wolf-Rayette. Coloration should also be light red with blue tinges

![image](https://user-images.githubusercontent.com/37888771/148308752-159d6cea-8a12-4326-8dcb-3246be858693.png)
![image](https://user-images.githubusercontent.com/37888771/148308760-7381d470-753b-47df-afb0-fd45b3664528.png)

**Comment by CrimsonDynamic** [comment]
Whoops article was off its a red super giant
