### ISSUE TITLE
Salarian Government

### ISSUE THREAD

**Issue by mstonefield** [Beyond-the-Relays/beyond_the_relays#41]
![image](https://user-images.githubusercontent.com/37888771/148310589-083d9ee4-7dd4-4bae-87ea-90d6f2d84891.png)
Should be science directorate

**Comment by CrimsonDynamic** [comment]
Added a specific Salarian Government
This is needed for every Empire it needs a custom Government because it chooses a random one from its available list.
Laid the foundation for that out
